name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"

            - name: Install Dependencies
              run: |
                pip install -r requirements.txt

            - name: Run Basic Check
              run: |
                python -m py_compile $(git ls-files '*.py')

            - name: Lint
              run: |
                pip install flake8
                flake8 . || true
            
            